workflows:
  ios-test-build:
    name: iOS Test Build via Codemagic
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
      # Variables for Code Signing should be configured on the Codemagic UI:
      # APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_PRIVATE_KEY
      groups:
        - appstore_credentials # Only required if you're code signing

    scripts:
      - name: Install Flutter packages
        script: |
          flutter packages pub get
          
      - name: Install iOS Pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Set up code signing (Optional / if set up)
        script: |
          # The following lines enable automatic code signing with App Store Connect credentials.
          # app-store-connect fetch-signing-files "YOUR_BUNDLE_ID" \
          #   --type IOS_APP_DEVELOPMENT \
          #   --create
          # xcode-project use-profiles
          echo "Bỏ qua code signing nếu build không cần chứng chỉ (để test thử)."

      - name: Build iOS IPA (Unsigned) và đóng gói thủ công
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/ios-test-app.ipa Payload
          cd ../../..

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - notify-email@domain.com # Thay đổi email của bạn
        notify:
          success: true
          failure: true
